### ISSUE TITLE
Phone keep asking to verify Google password for botting account

### ISSUE THREAD

**Issue by Lntnam** [PokemonGoF/PokemonGo-Bot-Backup#11]
Not sure if it's only me, but my phone keep asking me to verify password for the Google account that I am using for the bot, saying it was due to some account update.

I'm pretty sure I didn't update anything on that Google account.

It had also happened for the previous account, until I switch to the current one.

**Comment by xty** [comment]
This happens to me quite a lot, and one of the accounts that I used for [PokemonGo Map](https://github.com/PokemonGoMap/PokemonGo-Map) was affected too, but you always have the option of using a Pokémon Trainer Club account for botting.

**Comment by javajohnHub** [comment]
Me also...i dont know if it matters but i wait to relog into gmail until my bot is close enough to my loc.

**Comment by ravey-davey** [comment]
Whether it's coincidence or not, but every time I've used a PTC account, it's been banned within a week. However, my google account is now 3 weeks and still going...

**Comment by xty** [comment]
> Whether it's coincidence or not, but every time I've used a PTC account, it's been banned within a week. However, my google account is now 3 weeks and still going...

Mostly likely just a coincidence. I have been botting with a PTC account for almost 3 weeks now and haven't been banned to this date. It doesn't really make sense to pick on PTC accounts but turn a blind eye to Google accounts, don't you think?

**Comment by avexus** [comment]
@lntn same here.
@ravey-davey my google account is fine for now. have not used ptc account because too much trouble logging into the phone app

**Comment by Gobberwart** [comment]
@ravey-davey My ptc account is still going after 4 weeks botting so... shrug
I'd suggest don't use your primary google account for botting.
Not an issue with the bot per-se, closing this.
