### ISSUE TITLE
All the issues are gone. Now what?

### ISSUE THREAD

**Issue by xty** [PokemonGoF/PokemonGo-Bot-Backup#5]
As you can see, all the previous issues are erased due to an accident… While people are contacting GitHub to restore all the issues and PRs, in case that doesn't work out smoothly, I suggest everyone who has filed an issue in the past go retrieve the content of your issue tickets using Google's cache while you still can. To do this, you'll first need to get the URL of your issue by looking for it in the **contribution activity** section of your GitHub profile page. Next, do a Google search by pasting the URL into the search bar. Then, click on the downward arrow next to your URL in the search results, and select `Cached`.

![selection_002](https://cloud.githubusercontent.com/assets/11317451/18498737/6338f99c-7a6b-11e6-8f2e-007f790c9227.png)

Please note the cached page of your issue ticket might not be the most up-to-date version, but half a loaf is better than none. The best luck with restoring issues and PRs! :wink:

**Comment by MerlionRock** [comment]
I see blank... I thought Niantic going after this project....

**Comment by mjmadsen** [comment]
Waiting on github to restore out repository. Please be patient.

**Comment by joelgreen** [comment]
javajohn is a deep undercover agent for niantic

**Comment by davidakachaos** [comment]
Could this also explain why my fork seems to be from another project all of a sudden?
I forked this repo, and now it says:

```
forked from WicCaesar/PokemonGo-Auto-Pokestop
```

Strange?

**Comment by solderzzc** [comment]
He was the first one forked our first repo named PokemonGo-Auto-Pokestop

**Comment by brantje** [comment]
Deleting repo's don't happen by accident.
Afaik you have to confirm twice. And 2 times the repo name is displayed clearly.

**Comment by DBa2016** [comment]
You confirm once and you need to enter the repo name. But: in this case, the whole repository would be gone, not only issues and PRs.

**Comment by DBa2016** [comment]
@davidakachaos , @solderzzc : I can second this (fork pointing to the wrong repo). 

I cannot even create PRs against this repo anymore, it seems completely disconnected.

**Comment by brantje** [comment]
@DBa2016 We repushed all code.

**Comment by DBa2016** [comment]
so what do I need to do in order to create PRs? Refork the repo?

**Comment by cbogithub** [comment]
@javajohnHub fuck you

**Comment by DBa2016** [comment]
@cbogithub everyone makes mistakes. No need to get that personal nor rude.

**Comment by xty** [comment]
> I see blank... I thought Niantic going after this project....

I too thought for a moment that PokemonGo-Bot followed in [NecroBot](https://github.com/NecronomiconCoding/NecroBot)'s footsteps.

**Comment by cbogithub** [comment]
@DBa2016 this isn't mistake , thought this 's destruction
 @javajohnHub **is a Niantic spy**

**Comment by javajohnHub** [comment]
I forgive your remarks.

**Comment by Gobberwart** [comment]
I have removed/edited any comments which identify the individual responsible for the repo deletion. It was an accident, end of story.

**Comment by xty** [comment]
> I have removed/edited any comments which identify the individual responsible for the repo deletion. It was an accident, end of story.

Although I agree that it was unlikely a case of willful damage, other members of the community are entitled to understand the cause of the disruption and make their own judgement. Thinking others might be wrong doesn't give you the right to silence opinions different from yours. Censorship and cover-ups are not the way to go in a free community.

Now that the repo has been successfully restored, let's bring an end to this issue and move forward. Happy botting!

**Comment by Gobberwart** [comment]
@xiatianyu I completely disagree with you. There is no "cover-up" here, nor have I silenced any opinions. The facts are still the facts, however identifying an individual as being personally responsible is completely unnecessary, and has led to ridiculous targeted abuse/threats which, frankly, is disgusting. In future, think before you post.

**Comment by MerlionRock** [comment]
Let's move on.

At least the good news ->  PokemonGo-Bot **didn't** follow in NecroBot's footsteps. Cheers :)

**Comment by xty** [comment]
> There is no "cover-up" here, nor have I silenced any opinions.

If concealing the identity of the person responsible for the deletion of the repo is not a cover-up, what is it? 

> and has led to ridiculous targeted abuse/threats which, frankly, is disgusting.

As far as I can remember, you deleted the remarks made by @joelgreen and @brantje about you-know-who, one of which has attracted at least five :smile: and not a single :-1:. Obviously, while you find these remarks disgusting, others are taking it as a light-hearted joke. I don't know what threats you are talking about. The simple fact is you have been deleting comments based on your own liking, and that's what I call censorship.
